import { z } from 'zod';
import { channelSchema } from './channels';
import { ProtocolError } from './errors';
import {
  clockStateSchema,
  decisionMethodSchema,
  matchEventSchema,
  matchIdSchema,
  matchStateSchema,
  outcomeSideSchema,
  scoreValueSchema,
  sideSchema,
  targetSchema,
  techniqueSchema,
} from './match';
import {
  adminAlertSchema,
  channelSnapshotSchema,
  deviceStatusSchema,
  ringQueueSchema,
} from './snapshot';

/** Bumped when the wire format changes incompatibly. */
export const PROTOCOL_VERSION = 1;

const messageBase = {
  v: z.literal(PROTOCOL_VERSION),
  /** UUID v7, generated by the sender, so no coordination is needed. */
  id: z.uuid(),
  ts: z.int().nonnegative(),
  channel: channelSchema,
};

function serverMessage<T extends string, P extends z.ZodType>(type: T, payload: P) {
  return z.strictObject({
    ...messageBase,
    type: z.literal(type),
    /** Server-assigned, monotonic per channel. Lets a client detect a gap. */
    seq: z.int().nonnegative(),
    payload,
  });
}

export const serverMessageSchema = z.discriminatedUnion('type', [
  serverMessage('SNAPSHOT', channelSnapshotSchema),
  serverMessage('MATCH_STATE', matchStateSchema),
  serverMessage('MATCH_EVENT', matchEventSchema),
  serverMessage('QUEUE_UPDATE', ringQueueSchema),
  serverMessage('CLOCK', clockStateSchema),
  serverMessage('DEVICE_STATUS', deviceStatusSchema),
  serverMessage('ALERT', adminAlertSchema),
]);

export type ServerMessage = z.infer<typeof serverMessageSchema>;
export type ServerMessageType = ServerMessage['type'];

/**
 * Every command carries a `commandId` so a retry — a double-tap, a dropped
 * Wi-Fi packet, a replayed queue — cannot apply the same change twice.
 */
const matchCommandBase = {
  matchId: matchIdSchema,
  commandId: z.uuid(),
};

function clientMessage<T extends string, P extends z.ZodType>(type: T, payload: P) {
  return z.strictObject({
    ...messageBase,
    type: z.literal(type),
    payload,
  });
}

export const clientMessageSchema = z.discriminatedUnion('type', [
  clientMessage('CALL_MATCH', z.strictObject({ ...matchCommandBase })),
  clientMessage('START_MATCH', z.strictObject({ ...matchCommandBase })),
  clientMessage('PAUSE_MATCH', z.strictObject({ ...matchCommandBase })),
  clientMessage('RESUME_MATCH', z.strictObject({ ...matchCommandBase })),

  // Art. 7.6: side, area and technique accompany the value.
  clientMessage(
    'SCORE',
    z.strictObject({
      ...matchCommandBase,
      side: sideSchema,
      value: scoreValueSchema,
      target: targetSchema,
      technique: techniqueSchema,
    }),
  ),

  /**
   * Records the next penalty for one athlete.
   *
   * The level is deliberately absent. WKF Art. 10.2-10.3 fixes the sequence —
   * CHUI, CHUI, CHUI, HANSOKU CHUI, HANSOKU — so the scorer reports *that a
   * penalty happened* and the server walks that athlete's ladder. A console
   * that chose the level itself is how a bout ends up with four CHUIs.
   */
  clientMessage('PENALTY', z.strictObject({ ...matchCommandBase, side: sideSchema })),

  clientMessage('SENSHU', z.strictObject({ ...matchCommandBase, side: sideSchema })),

  /**
   * Withdraws an athlete's SENSHU advantage.
   *
   * The rulebook has the referee announce this explicitly — "AKA/AO SENSHU
   * TORIMASEN" (Art. 12.2.8) — so the operator records it as its own action
   * rather than the software inferring it. It applies when an athlete forfeits
   * the advantage for avoiding combat late in the bout (Art. 10.4.16) or when a
   * video review shows the opponent also scored, so the point was not unopposed
   * (Art. 12.2.9).
   */
  clientMessage('SENSHU_TORIMASEN', z.strictObject({ ...matchCommandBase, side: sideSchema })),

  /** The bout reached full time or an eight-point lead; the clock stops. */
  clientMessage('END_MATCH', z.strictObject({ ...matchCommandBase })),

  /** Art. 6 — one side failed to appear. */
  clientMessage('KIKEN', z.strictObject({ ...matchCommandBase, side: sideSchema })),

  clientMessage(
    'CONFIRM_RESULT',
    z.strictObject({
      ...matchCommandBase,
      winner: outcomeSideSchema,
      method: decisionMethodSchema,
    }),
  ),

  /**
   * Reverses a confirmed result so it can be entered again (blueprint §16,
   * "wrong winner recorded"). The original events stay in the log; this only
   * reopens the match.
   */
  clientMessage('VOID_RESULT', z.strictObject({ ...matchCommandBase, reason: z.string().min(1) })),

  /**
   * Undoes the most recent scoring action.
   *
   * This is what the event log was built for: the event is voided rather than
   * deleted, so the record of what the operator actually pressed survives, and
   * the derived state is recomputed. A mis-tap during a bout has to be
   * recoverable or the console is unusable.
   */
  clientMessage('UNDO_LAST', z.strictObject({ ...matchCommandBase })),

  /** A judge casting a vote or score via mobile QR code or judge device */
  clientMessage(
    'VOTE_FLAG',
    z.strictObject({
      ...matchCommandBase,
      judgeNo: z.int().min(1).max(7),
      side: sideSchema,
      akaScore: z.number().min(0).max(10).optional(),
      aoScore: z.number().min(0).max(10).optional(),
    }),
  ),

  /** Manual flag entry or override for Kata */
  clientMessage(
    'RECORD_FLAGS',
    z.strictObject({
      ...matchCommandBase,
      akaFlags: z.int().nonnegative(),
      aoFlags: z.int().nonnegative(),
    }),
  ),

  /** Recording an individual bout outcome in Team Kumite */
  clientMessage(
    'RECORD_TEAM_BOUT',
    z.strictObject({
      ...matchCommandBase,
      boutNo: z.int().positive(),
      winner: outcomeSideSchema,
      akaPoints: z.int().nonnegative(),
      aoPoints: z.int().nonnegative(),
      method: decisionMethodSchema,
    }),
  ),
]);

export type ClientMessage = z.infer<typeof clientMessageSchema>;
export type ClientMessageType = ClientMessage['type'];

/** Parses an inbound server frame, or throws a {@link ProtocolError}. */
export function parseServerMessage(input: unknown): ServerMessage {
  return parseWith(serverMessageSchema, 'SERVER', input);
}

/** Parses an inbound client command, or throws a {@link ProtocolError}. */
export function parseClientMessage(input: unknown): ClientMessage {
  return parseWith(clientMessageSchema, 'CLIENT', input);
}

function parseWith<T extends z.ZodType>(schema: T, direction: 'SERVER' | 'CLIENT', input: unknown) {
  const result = schema.safeParse(input);

  if (result.success) {
    return result.data as z.infer<T>;
  }

  throw new ProtocolError(
    'INVALID_MESSAGE',
    `Malformed ${direction} message: ${result.error.issues
      .map((issue) => `${issue.path.join('.') || '<root>'}: ${issue.message}`)
      .join('; ')}`,
    result.error.issues.map((issue) => ({
      path: issue.path.join('.'),
      message: issue.message,
      code: issue.code,
    })),
  );
}
