import {
  appendMatchEvent,
  assignCategoryToTatami,
  createAthlete,
  createCategory,
  createEvent,
  createPool,
  createRegistration,
  createTatami,
  createUser,
  getDrawGraph,
  listEvents,
  listParticipantsForCategory,
  lockDraw,
  migrate,
  saveDraw,
  setCategoryState,
  type Pool,
} from '@event-suite/db';
import { generateDraw, resolveDraw, type MatchOutcome } from '@event-suite/draw-engine';
import { getRuleset } from '@event-suite/rules-engine';
import { hashPassword } from './password';

/**
 * Seeds a tournament that is worth exploring.
 *
 *   pnpm seed
 *
 * Idempotent: it does nothing if an event already exists. To start over, run
 * `pnpm db:reset` and seed again.
 *
 * What it leaves behind, deliberately, is a spread of states rather than one
 * tidy happy path:
 *
 *   - a 16-entrant category, drawn, locked and on a ring, so a deeper two-rung
 *     repechage can be seen;
 *   - an 8-entrant category, drawn and locked, for the standard two bronzes;
 *   - a 5-entrant category, drawn and locked, where byes are visible;
 *   - two categories with no draw at all, so a draw can be generated by hand;
 *   - a small category already played out, so the results page and the medal
 *     table are not empty.
 *
 * Clubs repeat across entrants on purpose: club separation only has something
 * to do when they do.
 */

const FIRST_NAMES = [
  'Rahul', 'Arjun', 'Kiran', 'Vijay', 'Suresh', 'Manjunath', 'Pradeep', 'Nikhil',
  'Anil', 'Ravi', 'Deepak', 'Santosh', 'Harish', 'Ganesh', 'Mahesh', 'Prakash',
  'Sandeep', 'Vinay', 'Chetan', 'Yashwanth', 'Shreya', 'Ananya', 'Kavya', 'Divya',
  'Meghana', 'Nisha', 'Pooja', 'Sneha', 'Rakshitha', 'Bhavana',
];

const LAST_NAMES = [
  'Kumar', 'Shetty', 'Gowda', 'Rao', 'Naik', 'Hegde',
  'Patil', 'Reddy', 'Kulkarni', 'Bhat', 'Poojary', 'Acharya',
];

const CLUBS = [
  'Bengaluru Karate Academy',
  'Mysuru Shotokan Dojo',
  'Mangaluru Goju-Ryu Club',
  'Udupi District Karate Association',
  'Hubballi Kyokushinkan',
  'Belagavi Wado-Kai',
];

interface CategoryPlan {
  name: string;
  ageGroup: string;
  gender: 'MALE' | 'FEMALE' | 'MIXED';
  discipline?: 'KUMITE' | 'KATA' | 'TEAM_KATA' | 'TEAM_KUMITE';
  minWeightKg?: number;
  entrants: number;
  /** Seed the top four, the way an organiser with a ranking list would. */
  seedTopFour?: boolean;
  draw?: 'locked' | 'none';
  /** Ring to place it on once locked. */
  ring?: number;
  playOut?: boolean;
  bronzeMedals?: 1 | 2;
  rulesetId?: string;
}

const PLAN: readonly CategoryPlan[] = [
  {
    name: 'Senior Male -67kg',
    ageGroup: 'senior',
    gender: 'MALE',
    discipline: 'KUMITE',
    minWeightKg: 67,
    entrants: 16,
    seedTopFour: true,
    draw: 'locked',
    ring: 1,
  },
  {
    name: 'Senior Male Kata',
    ageGroup: 'senior',
    gender: 'MALE',
    discipline: 'KATA',
    entrants: 8,
    seedTopFour: true,
    draw: 'locked',
    ring: 1,
    rulesetId: 'WKF_KATA_2026',
  },
  {
    name: 'Senior Female Team Kata',
    ageGroup: 'senior',
    gender: 'FEMALE',
    discipline: 'TEAM_KATA',
    entrants: 4,
    draw: 'locked',
    ring: 2,
    rulesetId: 'WKF_TEAM_KATA_2026',
  },
  {
    name: 'Senior Male Team Kumite',
    ageGroup: 'senior',
    gender: 'MALE',
    discipline: 'TEAM_KUMITE',
    entrants: 4,
    draw: 'locked',
    ring: 3,
    rulesetId: 'WKF_TEAM_KUMITE_2026',
  },
  {
    name: 'Senior Female -55kg',
    ageGroup: 'senior',
    gender: 'FEMALE',
    discipline: 'KUMITE',
    minWeightKg: 55,
    entrants: 8,
    seedTopFour: true,
    draw: 'locked',
    ring: 2,
  },
  {
    name: 'Cadet Male -52kg',
    ageGroup: 'cadet',
    gender: 'MALE',
    discipline: 'KUMITE',
    minWeightKg: 52,
    entrants: 5,
    draw: 'locked',
    ring: 3,
  },
  { name: 'Junior Male -55kg', ageGroup: 'junior', gender: 'MALE', discipline: 'KUMITE', minWeightKg: 55, entrants: 8 },
  { name: 'Cadet Female -47kg', ageGroup: 'cadet', gender: 'FEMALE', discipline: 'KUMITE', minWeightKg: 47, entrants: 4 },
  {
    name: 'Sub-Junior Mixed -30kg',
    ageGroup: 'u14',
    gender: 'MIXED',
    discipline: 'KUMITE',
    minWeightKg: 30,
    entrants: 3,
    draw: 'locked',
    playOut: true,
  },
];


/** Deterministic name generator, so two runs produce the same tournament. */
function nameFor(index: number): string {
  const first = FIRST_NAMES[index % FIRST_NAMES.length] ?? 'Athlete';
  const last = LAST_NAMES[Math.floor(index / FIRST_NAMES.length) % LAST_NAMES.length] ?? 'Kumar';
  return `${first} ${last}`;
}

/** Two entrants per club, so club-mates exist to be separated. */
function clubFor(index: number): string {
  return CLUBS[Math.floor(index / 2) % CLUBS.length] ?? 'Independent';
}

async function seed(): Promise<void> {
  const pool = createPool();

  try {
    await migrate(pool);

    const existing = await listEvents(pool);
    if (existing.length > 0) {
      console.log(`[seed] ${existing.length} event(s) already present; nothing to do.`);
      console.log('[seed] run `pnpm db:reset` first if you want a clean tournament.');
      return;
    }

    const ruleset = getRuleset('WKF_KUMITE_2026');

    const operator = await createUser(pool, {
      name: 'Event Admin',
      email: 'admin@example.com',
      passwordHash: hashPassword('karate-admin'),
      role: 'EVENT_ADMIN',
    });

    const event = await createEvent(pool, {
      name: 'Karnataka State Karate Championship',
      venue: 'Koramangala Indoor Stadium, Bengaluru',
      rulesetId: ruleset.id,
    });

    for (const number of [1, 2, 3]) {
      await createTatami(pool, { eventId: event.id, number, name: `Tatami ${number}` });
    }

    let athleteIndex = 0;

    for (const plan of PLAN) {
      const isTeam = plan.discipline === 'TEAM_KATA' || plan.discipline === 'TEAM_KUMITE';
      const category = await createCategory(pool, {
        eventId: event.id,
        name: plan.name,
        ageGroup: plan.ageGroup,
        gender: plan.gender,
        discipline: plan.discipline ?? 'KUMITE',
        minWeightKg: plan.minWeightKg ?? null,
      });

      for (let entrant = 0; entrant < plan.entrants; entrant += 1) {
        const club = clubFor(entrant);
        const displayName = isTeam
          ? `${club} (Team ${String.fromCharCode(65 + (entrant % 2))})`
          : nameFor(athleteIndex++);

        const athlete = await createAthlete(pool, { displayName, clubName: club });

        await createRegistration(pool, {
          eventId: event.id,
          categoryId: category.id,
          athleteId: athlete.id,
          clubName: club,
        });
      }

      if (plan.draw !== 'locked') {
        console.log(`[seed] ${plan.name}: ${plan.entrants} entrants, no draw yet`);
        continue;
      }

      const participants = await listParticipantsForCategory(pool, category.id);
      const categoryRuleset = plan.rulesetId !== undefined ? getRuleset(plan.rulesetId) : ruleset;

      const graph = generateDraw(
        {
          categoryId: category.id,
          format: categoryRuleset.defaultFormat,
          participants,
          seeding: plan.seedTopFour === true ? manualSeeds(participants) : { mode: 'NONE' },
          separation: { by: 'CLUB', rule: 'FIRST_ROUND' },
          options: { bronzeMedals: plan.bronzeMedals ?? 2 },
        },
        categoryRuleset,
      );

      await saveDraw(pool, category.id, graph);
      await setCategoryState(pool, category.id, 'DRAW_GENERATED');
      await lockDraw(pool, category.id);
      await setCategoryState(pool, category.id, 'LOCKED');

      const bronzeBouts = graph.matches.filter((match) => match.bracketType === 'BRONZE').length;
      let line =
        `[seed] ${plan.name}: ${plan.entrants} entrants, ${graph.matches.length} matches, ` +
        `${graph.byeCount} bye(s), ${bronzeBouts} bronze bout(s)`;

      if (plan.ring !== undefined) {
        const tatami = await pool.query<{ id: string }>(
          'SELECT id FROM tatamis WHERE event_id = $1 AND number = $2',
          [event.id, plan.ring],
        );
        const tatamiId = tatami.rows[0]?.id;

        if (tatamiId !== undefined) {
          await assignCategoryToTatami(pool, {
            eventId: event.id,
            tatamiId,
            categoryId: category.id,
          });
          await setCategoryState(pool, category.id, 'ASSIGNED');
          line += `, on Tatami ${plan.ring}`;
        }
      }

      if (plan.playOut === true) {
        line += `, played out (${await playToCompletion(pool, category.id)} matches)`;
      }

      const warnings = graph.warnings.map((warning) => warning.code).join(', ');
      if (warnings !== '') line += ` [${warnings}]`;

      console.log(line);
    }

    console.log('');
    console.log(`[seed] "${event.name}" is ready.`);
    console.log(`[seed] sign in as ${operator.email} / karate-admin`);
    console.log('[seed] start everything with: pnpm dev');
  } finally {
    await pool.end();
  }
}

function manualSeeds(
  participants: ReadonlyArray<{ registrationId: string }>,
): { mode: 'MANUAL'; seeds: Array<{ registrationId: string; seed: number }> } {
  return {
    mode: 'MANUAL',
    seeds: participants.slice(0, 4).map((participant, index) => ({
      registrationId: participant.registrationId,
      seed: index + 1,
    })),
  };
}

/**
 * Plays a category to the end, top line winning every bout.
 *
 * Uses the same resolver the live server does, so the seeded result is one the
 * bracket engine actually agrees with rather than a hand-written podium.
 */
async function playToCompletion(pool: Pool, categoryId: string): Promise<number> {
  const graph = await getDrawGraph(pool, categoryId);
  if (graph === null) return 0;

  const results = new Map<string, MatchOutcome>();
  let played = 0;

  for (let step = 0; step <= graph.matches.length; step += 1) {
    const resolution = resolveDraw(graph, results);
    const matchId = resolution.readyMatchIds[0];
    if (matchId === undefined) break;

    const append = (type: string, payload: Record<string, unknown> = {}) =>
      appendMatchEvent(pool, { matchId, type, payload, actor: 'seed', deviceId: 'SEED' });

    await append('MATCH_START');
    await append('SCORE', { side: 'AKA', value: 3, target: 'JODAN', technique: 'KERI' });
    await append('MATCH_END');
    await append('RESULT_CONFIRM', { winner: 'AKA', method: 'POINTS' });

    results.set(matchId, { kind: 'WINNER', side: 'AKA' });
    played += 1;
  }

  return played;
}

void seed().catch((error: unknown) => {
  console.error('[seed] failed:', error);
  process.exitCode = 1;
});
